# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "675e75fcafc0db939c1084d68588e5c4"
name = "Auto-Discounter"
handle = "auto-discounter"
application_url = "https://hampton-fiber-forever-d.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "germiny.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://hampton-fiber-forever-d.trycloudflare.com/auth/callback",
  "https://hampton-fiber-forever-d.trycloudflare.com/auth/shopify/callback",
  "https://hampton-fiber-forever-d.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
